import React, { useEffect } from "react";
import { observer } from "mobx-react-lite";
import { useTranslation } from "react-i18next";
import {
  PageContainer,
  LanguageSelector,
  PageTitle,
  SectionTitle,
  SectionsContainer,
  Section,
} from "./styled";
import { ItemsView } from "@features/items/view";
import itemsStore from "@features/items/model";
import Button from "@shared/ui/Button/Button";
import { SimpleItemData } from "@features/items/view/types";

const ItemsPage: React.FC = () => {
  const { t, i18n } = useTranslation();
  const { items, loading, language, fetchItems, setLanguage } = itemsStore;

  useEffect(() => {
    fetchItems();
  }, [fetchItems, language]);

  const handleLanguageChange = (lang: string) => {
    setLanguage(lang);
    i18n.changeLanguage(lang);
  };

  const sampleItemIds: SimpleItemData[] = [
    { id: "iwsaa46", count: 5 },
    { id: "ikbtc31", upgrade: "70ffffff" },
    { id: "iabnb11", count: 3, upgrade: "7abcdef" },
  ];

  return (
    <PageContainer>
      <PageTitle>{t("pageTitle")}</PageTitle>

      <LanguageSelector>
        <Button
          $primary={language === "en"}
          onClick={() => handleLanguageChange("en")}
        >
          English
        </Button>
        <Button
          $primary={language === "ru"}
          onClick={() => handleLanguageChange("ru")}
        >
          Русский
        </Button>
      </LanguageSelector>

      <SectionsContainer>
        <Section>
          <SectionTitle>{t("itemsFromApi")}</SectionTitle>
          <ItemsView
            items={[
              {
                Code: "ikbtc31",
                Name: "Объединенный Бустер [Ранг 100",
                Desc: "United Booster Desc",
                Count: "1",
                ItemGrade: 5,
                IsSell: 1,
                IsExchange: 0,
                IsGround: 0,
                IsStore: 1,
                IsTime: 1,
                FireTol: 0,
                WaterTol: 0,
                SoilTol: 0,
                WindTol: 0,
                ExpertLim1: -1,
                LevelLim: 55,
                BoostSpd: 9,
                UpgradeMaxCount: 7,
                UpgradeNames: ["Талика Хаоса"],
                UpgradeDescriptions: ["Уменьшает шанс критичской атаки 45%"],
                DefFc: null,
                Civil: "Федерация Беллато",
                ItemClass: "Накидка",
                SpriteX: -1088,
                SpriteY: -512,
                SpriteFileName: "item-1-20.webp",
                EffectDescriptions: [
                  "Максимальное кол-во очков HP увелич. на 80%",
                  "Показатель защиты увелич. на 1%",
                  "Показатель урона увелич. на 50%",
                  "Параметр уклонения увелич. на 50 ед.",
                ],
              },
              {
                Code: "ikbtc31",
                Name: "Объединенный Бустер [Ранг 100",
                Desc: "United Booster Desc",
                Count: "1",
                ItemGrade: 5,
                IsSell: 1,
                IsExchange: 0,
                IsGround: 0,
                IsStore: 1,
                IsTime: 1,
                FireTol: 0,
                WaterTol: 0,
                SoilTol: 0,
                WindTol: 0,
                ExpertLim1: -1,
                LevelLim: 55,
                BoostSpd: 9,
                UpgradeMaxCount: 7,
                UpgradeNames: ["Талика Хаоса"],
                UpgradeDescriptions: ["Уменьшает шанс критичской атаки 45%"],
                DefFc: null,
                Civil: "Федерация Беллато",
                ItemClass: "Накидка",
                SpriteX: -1088,
                SpriteY: -512,
                SpriteFileName: "item-1-20.webp",
                EffectDescriptions: [
                  "Максимальное кол-во очков HP увелич. на 80%",
                  "Показатель защиты увелич. на 1%",
                  "Показатель урона увелич. на 50%",
                  "Параметр уклонения увелич. на 50 ед.",
                ],
              },
              {
                Code: "ikbgl01",
                Name: "Расовая Накидка",
                Desc: "Strength Booster Desc",
                Count: "1",
                ItemGrade: 5,
                IsSell: 1,
                IsExchange: 0,
                IsGround: 0,
                IsStore: 1,
                IsTime: 1,
                FireTol: 0,
                WaterTol: 0,
                SoilTol: 0,
                WindTol: 0,
                ExpertLim1: -1,
                LevelLim: 1,
                BoostSpd: 0,
                UpgradeMaxCount: 7,
                UpgradeNames: ["Талика Хаоса"],
                UpgradeDescriptions: ["Уменьшает шанс критичской атаки 75%"],
                DefFc: null,
                Civil: "Федерация Беллато",
                ItemClass: "Накидка",
                SpriteX: -960,
                SpriteY: -512,
                SpriteFileName: "item-1-20.webp",
                EffectDescriptions: [
                  "Параметр скорости передвижения увелич. на 1 ед.",
                  "Показатель урона увелич. на 30%",
                  "Вероятность критической атаки увелич. на 30 ед.",
                ],
              },
              {
                Code: "ireyl01",
                Name: "Кусок Желтой Стружки",
                Desc: "Куски и цельная стружка используются в производстве и сборке предметов. Из кусков можно собрать цельную стружку.",
                Count: "44",
                IsSell: 1,
                IsExchange: 1,
                IsGround: 1,
                IsStore: 1,
                IsTime: 0,
                UpgradeNames: [],
                UpgradeDescriptions: [],
                DefFc: null,
                ItemClass: "Ресурсы",
                SpriteX: -1536,
                SpriteY: -64,
                SpriteFileName: "item-1-9.webp",
                EffectDescriptions: [],
              },
              {
                Code: "irepu01",
                Name: "Кусок Лиловой Стружки",
                Desc: "Куски и цельная стружка используются в производстве и сборке предметов. Из кусков можно собрать цельную стружку.",
                Count: "44",
                IsSell: 1,
                IsExchange: 1,
                IsGround: 1,
                IsStore: 1,
                IsTime: 0,
                UpgradeNames: [],
                UpgradeDescriptions: [],
                DefFc: null,
                ItemClass: "Ресурсы",
                SpriteX: -1600,
                SpriteY: -64,
                SpriteFileName: "item-1-9.webp",
                EffectDescriptions: [],
              },
              {
                Code: "irewh01",
                Name: "Кусок Белой Стружки",
                Desc: "Куски и цельная стружка используются в производстве и сборке предметов. Из кусков можно собрать цельную стружку.",
                Count: "44",
                IsSell: 1,
                IsExchange: 1,
                IsGround: 1,
                IsStore: 1,
                IsTime: 0,
                UpgradeNames: [],
                UpgradeDescriptions: [],
                DefFc: null,
                ItemClass: "Ресурсы",
                SpriteX: -1664,
                SpriteY: -64,
                SpriteFileName: "item-1-9.webp",
                EffectDescriptions: [],
              },
              {
                Code: "irebw01",
                Name: "Кусок Бархатной Стружки",
                Desc: "Куски и цельная стружка используются в производстве и сборке предметов. Из кусков можно собрать цельную стружку.",
                Count: "44",
                IsSell: 1,
                IsExchange: 1,
                IsGround: 1,
                IsStore: 1,
                IsTime: 0,
                UpgradeNames: [],
                UpgradeDescriptions: [],
                DefFc: null,
                ItemClass: "Ресурсы",
                SpriteX: -1728,
                SpriteY: -64,
                SpriteFileName: "item-1-9.webp",
                EffectDescriptions: [],
              },
              {
                Code: "ireol01",
                Name: "Кусок Оливковой Стружки",
                Desc: "Куски и цельная стружка используются в производстве и сборке предметов. Из кусков можно собрать цельную стружку.",
                Count: "44",
                IsSell: 1,
                IsExchange: 1,
                IsGround: 1,
                IsStore: 1,
                IsTime: 0,
                UpgradeNames: [],
                UpgradeDescriptions: [],
                DefFc: null,
                ItemClass: "Ресурсы",
                SpriteX: -1792,
                SpriteY: -64,
                SpriteFileName: "item-1-9.webp",
                EffectDescriptions: [],
              },
              {
                Code: "irena01",
                Name: "Кусок Морской Стружки",
                Desc: "Куски и цельная стружка используются в производстве и сборке предметов. Из кусков можно собрать цельную стружку.",
                Count: "44",
                IsSell: 1,
                IsExchange: 1,
                IsGround: 1,
                IsStore: 1,
                IsTime: 0,
                UpgradeNames: [],
                UpgradeDescriptions: [],
                DefFc: null,
                ItemClass: "Ресурсы",
                SpriteX: -1856,
                SpriteY: -64,
                SpriteFileName: "item-1-9.webp",
                EffectDescriptions: [],
              },
              {
                Code: "irchr01",
                Name: "Праздничный Изумруд Изобилия",
                Desc: "Изумруд доступен только во время Нового Года. Увеличивает опыт, получаемый от убийства монстров. Нельзя выбросить или продать исчезает после праздников.",
                Count: "44",
                IsSell: 1,
                IsExchange: 0,
                IsGround: 0,
                IsStore: 1,
                IsTime: 0,
                UpgradeNames: [],
                UpgradeDescriptions: [],
                DefFc: null,
                ItemClass: "Ресурсы",
                SpriteX: -1920,
                SpriteY: -64,
                SpriteFileName: "item-1-9.webp",
                EffectDescriptions: [
                  "Опыт получаемый при убийстве монстров увелич. на 20%",
                ],
              },
              {
                Code: "irchr02",
                Name: "Праздничный Изумруд Утешения",
                Desc: "Изумруд доступен только во время Нового Года. Снижает ограничения по уровням всех предметов. Нельзя выбросить или продать исчезает после праздников.",
                Count: "44",
                IsSell: 1,
                IsExchange: 0,
                IsGround: 0,
                IsStore: 1,
                IsTime: 0,
                UpgradeNames: [],
                UpgradeDescriptions: [],
                DefFc: null,
                ItemClass: "Ресурсы",
                SpriteX: -1984,
                SpriteY: -64,
                SpriteFileName: "item-1-9.webp",
                EffectDescriptions: [
                  "Требуемый уровень для экипируемых предметов увелич. на 5",
                ],
              },
              {
                Code: "irval01",
                Name: "Цветы",
                Desc: "Увеличивает на 10% опыт,получаемый за охоту. Вовможно использовать с Изумрудами Изабилия.",
                Count: "44",
                IsSell: 1,
                IsExchange: 0,
                IsGround: 0,
                IsStore: 1,
                IsTime: 1,
                UpgradeNames: [],
                UpgradeDescriptions: [],
                DefFc: null,
                ItemClass: "Ресурсы",
                SpriteX: 0,
                SpriteY: -128,
                SpriteFileName: "item-1-9.webp",
                EffectDescriptions: [
                  "Опыт получаемый при убийстве монстров увелич. на 10%",
                ],
              },
              {
                Code: "ircza02",
                Name: "Искрящийся Рубин",
                Desc: "<#fff Шансы Модификации><br>Экипировка<br><#0f0 55> | <#0f0 55> | <#0f0 45> | <#0f0 40> | <#f00 20> | <#f00 15> | - |<br>Экипировка Тип Б имеет на 5% больше шансов<br>Стихийная Бижутерия<br><#ff0 80% на всех рангах><br>Бижутерия Зверя<br><#ff0 60% на всех рангах>",
                Count: "44",
                IsSell: 1,
                IsExchange: 1,
                IsGround: 1,
                IsStore: 1,
                IsTime: 0,
                UpgradeNames: [],
                UpgradeDescriptions: [],
                DefFc: null,
                ItemClass: "Ресурсы",
                SpriteX: -64,
                SpriteY: -128,
                SpriteFileName: "item-1-9.webp",
                EffectDescriptions: [],
              },
              {
                Code: "irczb02",
                Name: "Кристальный Алмаз",
                Desc: "<#fff Шансы Модификации><br>Экипировка<br><#0f0 55> | <#0f0 55> | <#0f0 45> | <#0f0 40> | <#f00 20> | <#f00 15> | - |<br>Экипировка Тип Б имеет на 5% больше шансов<br>Стихийная Бижутерия<br><#ff0 80% на всех рангах><br>Бижутерия Зверя<br><#ff0 60% на всех рангах>",
                Count: "44",
                IsSell: 1,
                IsExchange: 1,
                IsGround: 1,
                IsStore: 1,
                IsTime: 0,
                UpgradeNames: [],
                UpgradeDescriptions: [],
                DefFc: null,
                ItemClass: "Ресурсы",
                SpriteX: -128,
                SpriteY: -128,
                SpriteFileName: "item-1-9.webp",
                EffectDescriptions: [],
              },
              {
                Code: "irczc02",
                Name: "Чайный Топаз",
                Desc: "<#fff Шансы Модификации><br>Экипировка<br><#0f0 55> | <#0f0 55> | <#0f0 45> | <#0f0 40> | <#f00 20> | <#f00 15> | - |<br>Экипировка Тип Б имеет на 5% больше шансов<br>Стихийная Бижутерия<br><#ff0 80% на всех рангах><br>Бижутерия Зверя<br><#ff0 60% на всех рангах>",
                Count: "44",
                IsSell: 1,
                IsExchange: 1,
                IsGround: 1,
                IsStore: 1,
                IsTime: 0,
                UpgradeNames: [],
                UpgradeDescriptions: [],
                DefFc: null,
                ItemClass: "Ресурсы",
                SpriteX: -192,
                SpriteY: -128,
                SpriteFileName: "item-1-9.webp",
                EffectDescriptions: [],
              },
              {
                Code: "irczd02",
                Name: "Черный Обсидиан",
                Desc: "<#fff Шансы Модификации><br>Экипировка<br><#0f0 55> | <#0f0 55> | <#0f0 45> | <#0f0 40> | <#f00 20> | <#f00 15> | - |<br>Экипировка Тип Б имеет на 5% больше шансов<br>Стихийная Бижутерия<br><#ff0 80% на всех рангах><br>Бижутерия Зверя<br><#ff0 60% на всех рангах>",
                Count: "44",
                IsSell: 1,
                IsExchange: 1,
                IsGround: 1,
                IsStore: 1,
                IsTime: 0,
                UpgradeNames: [],
                UpgradeDescriptions: [],
                DefFc: null,
                ItemClass: "Ресурсы",
                SpriteX: -256,
                SpriteY: -128,
                SpriteFileName: "item-1-9.webp",
                EffectDescriptions: [],
              },
              {
                Code: "ircza03",
                Name: "Рубин Удачи",
                Desc: "<#fff Шансы Модификации><br>Экипировка<br><#0f0 60> | <#0f0 60> | <#0f0 50> | <#0f0 45> | <#ff0 30> | <#f00 20> | - |<br>Экипировка Тип Б имеет на 5% больше шансов<br>Стихийная Бижутерия<br><#0f0 90% на всех рангах><br>Бижутерия Зверя<br><#ff0 70% на всех рангах>",
                Count: "44",
                IsSell: 1,
                IsExchange: 0,
                IsGround: 0,
                IsStore: 1,
                IsTime: 0,
                UpgradeNames: [],
                UpgradeDescriptions: [],
                DefFc: null,
                ItemClass: "Ресурсы",
                SpriteX: -320,
                SpriteY: -128,
                SpriteFileName: "item-1-9.webp",
                EffectDescriptions: [],
              },
              {
                Code: "irczb03",
                Name: "Алмаз Удачи",
                Desc: "<#fff Шансы Модификации><br>Экипировка<br><#0f0 60> | <#0f0 60> | <#0f0 50> | <#0f0 45> | <#ff0 30> | <#f00 20> | - |<br>Экипировка Тип Б имеет на 5% больше шансов<br>Стихийная Бижутерия<br><#0f0 90% на всех рангах><br>Бижутерия Зверя<br><#ff0 70% на всех рангах>",
                Count: "44",
                IsSell: 1,
                IsExchange: 0,
                IsGround: 0,
                IsStore: 1,
                IsTime: 0,
                UpgradeNames: [],
                UpgradeDescriptions: [],
                DefFc: null,
                ItemClass: "Ресурсы",
                SpriteX: -384,
                SpriteY: -128,
                SpriteFileName: "item-1-9.webp",
                EffectDescriptions: [],
              },
              {
                Code: "irczc03",
                Name: "Топаз Удачи",
                Desc: "<#fff Шансы Модификации><br>Экипировка<br><#0f0 60> | <#0f0 60> | <#0f0 50> | <#0f0 45> | <#ff0 30> | <#f00 20> | - |<br>Экипировка Тип Б имеет на 5% больше шансов<br>Стихийная Бижутерия<br><#0f0 90% на всех рангах><br>Бижутерия Зверя<br><#ff0 70% на всех рангах>",
                Count: "44",
                IsSell: 1,
                IsExchange: 0,
                IsGround: 0,
                IsStore: 1,
                IsTime: 0,
                UpgradeNames: [],
                UpgradeDescriptions: [],
                DefFc: null,
                ItemClass: "Ресурсы",
                SpriteX: -448,
                SpriteY: -128,
                SpriteFileName: "item-1-9.webp",
                EffectDescriptions: [],
              },
              {
                Code: "irczd03",
                Name: "Обсидиан Удачи",
                Desc: "<#fff Шансы Модификации><br>Экипировка<br><#0f0 60> | <#0f0 60> | <#0f0 50> | <#0f0 45> | <#ff0 30> | <#f00 20> | - |<br>Экипировка Тип Б имеет на 5% больше шансов<br>Стихийная Бижутерия<br><#0f0 90% на всех рангах><br>Бижутерия Зверя<br><#ff0 70% на всех рангах>",
                Count: "44",
                IsSell: 1,
                IsExchange: 0,
                IsGround: 0,
                IsStore: 1,
                IsTime: 0,
                UpgradeNames: [],
                UpgradeDescriptions: [],
                DefFc: null,
                ItemClass: "Ресурсы",
                SpriteX: -512,
                SpriteY: -128,
                SpriteFileName: "item-1-9.webp",
                EffectDescriptions: [],
              },
              {
                Code: "irres01",
                Name: "Алый Камень",
                Desc: "Недавно обнаруженный кристаллит улучшенного качества. Используется для производства брони С-класса.",
                Count: "44",
                IsSell: 1,
                IsExchange: 0,
                IsGround: 0,
                IsStore: 1,
                IsTime: 0,
                UpgradeNames: [],
                UpgradeDescriptions: [],
                DefFc: null,
                ItemClass: "Ресурсы",
                SpriteX: -704,
                SpriteY: -128,
                SpriteFileName: "item-1-9.webp",
                EffectDescriptions: [],
              },
              {
                Code: "ircsa05",
                Name: "Изумруд_Изобилия_[1_день",
                Desc: "Таинственный материал, получаемый в процессе очистки руды. Увеличивает получаемые очки боевого опыта на 10%. В совокупности не более 50% увеличения. Действует 24 часа.",
                Count: "11",
                IsSell: 1,
                IsExchange: 0,
                IsGround: 0,
                IsStore: 1,
                IsTime: 1,
                UpgradeNames: [],
                UpgradeDescriptions: [],
                DefFc: null,
                ItemClass: "Ресурсы",
                SpriteX: -576,
                SpriteY: -128,
                SpriteFileName: "item-1-9.webp",
                EffectDescriptions: [
                  "Опыт получаемый при убийстве монстров увелич. на 20%",
                ],
              },
              {
                Code: "iibnb01",
                Name: "Кольцо Ярости ",
                Desc: "<#8ae Рецепт пробуждения:><br><#2FB  • Кольцо Огня [15] - 1 шт<br> • Кольцо Воды [15] - 1 шт<br> • Кольцо Земли [15] - 1 шт<br> • Кольцо Воздуха [15] - 1 шт>",
                Count: "1",
                ItemGrade: 0,
                IsSell: 1,
                IsExchange: 1,
                IsGround: 1,
                IsStore: 1,
                IsTime: 0,
                FireTol: 0,
                WaterTol: 0,
                SoilTol: 0,
                WindTol: 0,
                LevelLim: 1,
                UpgradeNames: ["Талика Невежества"],
                UpgradeDescriptions: ["Увеличивает силу атаки на 150%"],
                DefFc: null,
                Civil: "Федерация Беллато",
                ItemClass: "Кольцо",
                SpriteX: -512,
                SpriteY: -128,
                SpriteFileName: "item-1-20.webp",
                EffectDescriptions: [
                  "Показатель урона увелич. на 15%",
                  "Показатель защиты увелич. на 15%",
                  "Параметр скорости передвижения увелич. на 1 ед.",
                ],
              },
              {
                Code: "iibnc01",
                Name: "Кольцо Эгиды ",
                Desc: "<#8ae Рецепт пробуждения:><br><#2FB  • Кольцо Огня [15] - 1 шт<br> • Кольцо Воды [15] - 1 шт<br> • Кольцо Земли [15] - 1 шт<br> • Кольцо Воздуха [15] - 1 шт>",
                Count: "1",
                ItemGrade: 0,
                IsSell: 1,
                IsExchange: 1,
                IsGround: 1,
                IsStore: 1,
                IsTime: 0,
                FireTol: 0,
                WaterTol: 0,
                SoilTol: 0,
                WindTol: 0,
                LevelLim: 1,
                UpgradeNames: ["Талика Невежества"],
                UpgradeDescriptions: ["Увеличивает силу атаки на 150%"],
                DefFc: null,
                Civil: "Федерация Беллато",
                ItemClass: "Кольцо",
                SpriteX: -576,
                SpriteY: -128,
                SpriteFileName: "item-1-20.webp",
                EffectDescriptions: [
                  "Показатель урона увелич. на 15%",
                  "Показатель защиты увелич. на 15%",
                  "Максимальное кол-во очков HP увелич. на 10%",
                ],
              },
              {
                Code: "iibnd01",
                Name: "Кольцо Мародера ",
                Desc: "<#8ae Рецепт пробуждения:><br><#2FB  • Кольцо Огня [15] - 1 шт<br> • Кольцо Воды [15] - 1 шт<br> • Кольцо Земли [15] - 1 шт<br> • Кольцо Воздуха [15] - 1 шт>",
                Count: "1",
                ItemGrade: 0,
                IsSell: 1,
                IsExchange: 1,
                IsGround: 1,
                IsStore: 1,
                IsTime: 0,
                FireTol: 0,
                WaterTol: 0,
                SoilTol: 0,
                WindTol: 0,
                LevelLim: 1,
                UpgradeNames: ["Талика Невежества"],
                UpgradeDescriptions: ["Увеличивает силу атаки на 2%"],
                DefFc: null,
                Civil: "Федерация Беллато",
                ItemClass: "Кольцо",
                SpriteX: -640,
                SpriteY: -128,
                SpriteFileName: "item-1-20.webp",
                EffectDescriptions: [
                  "Показатель урона увелич. на 15%",
                  "Показатель защиты увелич. на 15%",
                  "Переводит повреждения от атак в HP увелич. на 5%",
                ],
              },
              {
                Code: "iibne01",
                Name: "Кольцо Демона ",
                Desc: "<#8ae Рецепт пробуждения:><br><#2FB  • Кольцо Огня [15] - 1 шт<br> • Кольцо Воды [15] - 1 шт<br> • Кольцо Земли [15] - 1 шт<br> • Кольцо Воздуха [15] - 1 шт>",
                Count: "1",
                ItemGrade: 0,
                IsSell: 1,
                IsExchange: 1,
                IsGround: 1,
                IsStore: 1,
                IsTime: 0,
                FireTol: 0,
                WaterTol: 0,
                SoilTol: 0,
                WindTol: 0,
                LevelLim: 1,
                UpgradeNames: ["Талика Невежества"],
                UpgradeDescriptions: ["Увеличивает силу атаки на 50%"],
                DefFc: null,
                Civil: "Федерация Беллато",
                ItemClass: "Кольцо",
                SpriteX: -768,
                SpriteY: -128,
                SpriteFileName: "item-1-20.webp",
                EffectDescriptions: [
                  "Показатель урона увелич. на 15%",
                  "Показатель защиты увелич. на 15%",
                  "Параметр уклонения увелич. на 15 ед.",
                ],
              },
              {
                Code: "iabnb11",
                Name: "Клипсы Ярости",
                Desc: "<#8ae Бонус от двух частей:><br><#ff0 30 Атаки, 30 Защиты>",
                Count: "1",
                ItemGrade: 7,
                IsSell: 1,
                IsExchange: 1,
                IsGround: 1,
                IsStore: 1,
                IsTime: 0,
                FireTol: 5,
                WaterTol: 5,
                SoilTol: 5,
                WindTol: 5,
                LevelLim: 1,
                UpgradeNames: [],
                UpgradeDescriptions: [],
                DefFc: null,
                Civil: "Федерация Беллато",
                ItemClass: "Амулет",
                SpriteX: -1152,
                SpriteY: -256,
                SpriteFileName: "item-1-20.webp",
                EffectDescriptions: [
                  "Показатель урона увелич. на 15%",
                  "Показатель защиты увелич. на 15%",
                  "Параметр скорости передвижения увелич. на 1 ед.",
                ],
              },
              {
                Code: "iabnc11",
                Name: "Клипсы Эгиды",
                Desc: "<#8ae Бонус от двух частей:><br><#ff0 30 Атаки, 30 Защиты, 10 ХП>",
                Count: "1",
                ItemGrade: 7,
                IsSell: 1,
                IsExchange: 1,
                IsGround: 1,
                IsStore: 1,
                IsTime: 0,
                FireTol: 5,
                WaterTol: 5,
                SoilTol: 5,
                WindTol: 5,
                LevelLim: 1,
                UpgradeNames: [],
                UpgradeDescriptions: [],
                DefFc: null,
                Civil: "Федерация Беллато",
                ItemClass: "Амулет",
                SpriteX: -1216,
                SpriteY: 0,
                SpriteFileName: "item-1-20.webp",
                EffectDescriptions: [
                  "Показатель урона увелич. на 15%",
                  "Показатель защиты увелич. на 15%",
                  "Максимальное кол-во очков HP увелич. на 10%",
                ],
              },
              {
                Code: "iabnd11",
                Name: "Клипсы Мародера",
                Desc: "<#8ae Бонус от двух частей:><br><#ff0 30 Атаки, 30 Защиты, 10 Вампиризма>",
                Count: "1",
                ItemGrade: 7,
                IsSell: 1,
                IsExchange: 1,
                IsGround: 1,
                IsStore: 1,
                IsTime: 0,
                FireTol: 5,
                WaterTol: 5,
                SoilTol: 5,
                WindTol: 5,
                LevelLim: 1,
                UpgradeNames: [],
                UpgradeDescriptions: [],
                DefFc: null,
                Civil: "Федерация Беллато",
                ItemClass: "Амулет",
                SpriteX: 0,
                SpriteY: -64,
                SpriteFileName: "item-1-20.webp",
                EffectDescriptions: [
                  "Показатель урона увелич. на 15%",
                  "Показатель защиты увелич. на 15%",
                  "Переводит повреждения от атак в HP увелич. на 5%",
                ],
              },
              {
                Code: "iwkaa01",
                Name: "1 GR] [Тип Б] Световой Меч [30",
                Desc: "Type C Weapon Desc",
                Count: "1",
                ItemGrade: 1,
                IsSell: 1,
                IsExchange: 1,
                IsGround: 1,
                IsStore: 1,
                IsTime: 0,
                GAMinAF: 729,
                GAMaxAF: 804,
                MAMinAF: 0,
                MAMaxAF: 0,
                FireTol: 0,
                WaterTol: 0,
                SoilTol: 0,
                WindTol: 0,
                ExpertLim1: 17,
                LevelLim: 30,
                ActiveEffLv: 0,
                ActiveProb: 0,
                UpgradeMaxCount: 7,
                UpgradeNames: ["Талика Невежества"],
                UpgradeDescriptions: ["Увеличивает силу атаки на 50%"],
                ExpertID1: "Ближний Навык",
                WeaponType: "Клинок",
                DefFc: null,
                Civil: "Все",
                ItemClass: "Оружие",
                SpriteX: 0,
                SpriteY: -64,
                SpriteFileName: "item-1-1.webp",
                EffectDescriptions: [
                  "Вероятность блокирования урона щитом увелич. на 12 ед.",
                ],
              },
              {
                Code: "iwjaa01",
                Name: "1 GR] [Тип Б] Молот [30",
                Desc: "Type C Weapon Desc",
                Count: "1",
                ItemGrade: 1,
                IsSell: 1,
                IsExchange: 1,
                IsGround: 1,
                IsStore: 1,
                IsTime: 0,
                GAMinAF: 729,
                GAMaxAF: 804,
                MAMinAF: 0,
                MAMaxAF: 0,
                FireTol: 0,
                WaterTol: 0,
                SoilTol: 0,
                WindTol: 0,
                ExpertLim1: 17,
                LevelLim: 30,
                ActiveEffLv: 0,
                ActiveProb: 0,
                UpgradeMaxCount: 7,
                UpgradeNames: ["Талика Невежества"],
                UpgradeDescriptions: ["Увеличивает силу атаки на 50%"],
                ExpertID1: "Ближний Навык",
                WeaponType: "Булава",
                DefFc: null,
                Civil: "Все",
                ItemClass: "Оружие",
                SpriteX: -64,
                SpriteY: -64,
                SpriteFileName: "item-1-1.webp",
                EffectDescriptions: ["Показатель защиты увелич. на 30%"],
              },
              {
                Code: "iwsaa01",
                Name: "1 GR] [Тип Б] Энергомеч [30",
                Desc: "Type C Weapon Desc",
                Count: "1",
                ItemGrade: 1,
                IsSell: 1,
                IsExchange: 1,
                IsGround: 1,
                IsStore: 1,
                IsTime: 0,
                GAMinAF: 729,
                GAMaxAF: 804,
                MAMinAF: 0,
                MAMaxAF: 0,
                FireTol: 0,
                WaterTol: 0,
                SoilTol: 0,
                WindTol: 0,
                ExpertLim1: 17,
                LevelLim: 30,
                ActiveEffLv: 0,
                ActiveProb: 0,
                UpgradeMaxCount: 7,
                UpgradeNames: ["Талика Невежества"],
                UpgradeDescriptions: ["Увеличивает силу атаки на 75%"],
                ExpertID1: "Ближний Навык",
                WeaponType: "Меч",
                DefFc: null,
                Civil: "Все",
                ItemClass: "Оружие",
                SpriteX: -128,
                SpriteY: -64,
                SpriteFileName: "item-1-1.webp",
                EffectDescriptions: ["Параметр уклонения увелич. на 20 ед."],
              },
            ]}
            loading={loading}
            language={language}
            onChangeLanguage={handleLanguageChange}
          />
        </Section>

        <Section>
          <SectionTitle>{t("itemsById")}</SectionTitle>
          <ItemsView
            itemIds={sampleItemIds}
            loading={loading}
            language={language}
            onChangeLanguage={handleLanguageChange}
          />
        </Section>
      </SectionsContainer>
    </PageContainer>
  );
};

export default observer(ItemsPage);
